dist: trusty
os:
  - linux
services:
  - docker
language: generic
jdk:
  - oraclejdk8
sudo: false
cache:
  directories:
    - $HOME/.gradle
env:
  global:
    - SPRING_OUTPUT_ANSI_ENABLED=ALWAYS
    - SPRING_JPA_SHOW_SQL=false
    - TERM=dumb
before_install:
  - jdk_switcher use oraclejdk8
  - java -version
  - sudo /etc/init.d/mysql stop
  - sudo /etc/init.d/postgresql stop
install:
script:
  - chmod +x gradlew
  - ./gradlew clean test --stacktrace --info
  - ./gradlew sonarqube --no-daemon -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.login=$SONAR_TOKEN -Dsonar.organization=adyen -Dsonar.pullrequest.branch=$TRAVIS_BRANCH -Dsonar.pullrequest.key=$TRAVIS_PULL_REQUEST -Dsonar.pullrequest.base=develop -Dsonar.pullrequest.provider=github -Dsonar.pullrequest.github.repository=$TRAVIS_REPO_SLUG -Dsonar.pullrequest.github.endpoint=https://api.github.com/
  - ./gradlew cucumberTest --stacktrace --info
  - ./gradlew bootRepackage -Pprod -x test

notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
